<<<<<<< HEAD
eureka: 
  client:
    register-with-eureka: false
    fetch-registry: false
server:
=======
eureka: 
  client:
    register-with-eureka: false
    fetch-registry: false
server:
>>>>>>> 41d800b8c58ee17a9957d985d53e4b53ee67a7e3
  port: 8761