spring:
  application:
   name: GETAWAY-SERVICE
    
  cloud:
   gateway:
     routes:
      - id: r1
        uri: lb://ORDER-SERVICE
        predicates:
          - Path=/order/**
      - id: r1
        uri: lb://PAYMENT-SERVICE
        predicates:
          - Path=/payment/**
    

    
server:
 port: 2525
 